AWSTemplateFormatVersion: '2010-09-09'
Description: API Failover using Route 53, CloudWatch Alarm, and Lambda
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: python3.9
    MemorySize: 512
    Timeout: 30

Parameters:
  HostedZoneId:
    Description: Hosted zone id
    Type: String
  HostedZoneName:
    Description: Name of hosted zone (must have a . at the end)
    Type: String
  DRAPIDomainName:
    Description: Domain name of api gateway in disaster recovery region
    Type: String
  DRHostedZoneId:
    Description: Hosted zone id for disaster recovery region
    Type: String
  DRSUBDomainName:
    Description: Sub domain name of disaster recovery region
    Type: String
  PRAPIDomainName:
    Description: Domain name of api in primary region
    Type: String
  PRHostedZoneId:
    Description: Hosted zone id for primary region
    Type: String
  PRSUBDomainName:
    Description: Sub domain name of primary region
    Type: String
  PRInvokeAPIURL:
    Description: Invoke url of primary api gateway
    Type: String
  AdminEmail:
    Description: Email of admin
    Type: String
  SecondaryUserPoolId:
    Description: User pool id of secondary stack
    Type: String
  DRRegion:
    Description: Disaster recovery region
    Type: String
    Default: eu-west-1
  PrimaryRegion:
    Description: Disaster recovery region
    Type: String
    Default: eu-central-1
  SNSNotificationTopicSecondary:
    Description: SNS notification topic arn in secondary region
    Type: String
  SNSNotificationTopicPrimary:
    Description: SNS notification topic arn in primary region
    Type: String
  DRCognitoAuthEndpoint:
    Description: authentication endpoint of cognito in secondary region
    Type: String
  DRCallBackUrlEndpoint:
    Description: callback url for cognito in secondary region
    Type: String
  DRClientId:
    Description: cognito client id in secondary region
    Type: String
  DRClientSecret:
    Description: cognito client secret in secondary region
    Type: String
  DRWebsocketEndpoint:
    Description: api websocket endpoint in secondary region
    Type: String


Resources:
  Route53HealthCheck:   # Route 53 Health Check for Primary API
    Type: AWS::Route53::HealthCheck
    Properties:
      HealthCheckConfig:
        Type: HTTPS
        ResourcePath: /Prod/health
        FullyQualifiedDomainName: !Ref PRInvokeAPIURL
        RequestInterval: 10
        FailureThreshold: 2
      HealthCheckTags:
        - Key: Name
          Value: Primary API Health Check

  Route53FailoverRecordPrimary: # Route 53 Failover DNS Record for primary api gateway
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Ref HostedZoneName
      Name: !Ref PRSUBDomainName
      Type: A
      SetIdentifier: Primary
      HealthCheckId: !Ref Route53HealthCheck
      Failover: PRIMARY
      AliasTarget:
        DNSName: !Ref PRAPIDomainName
        HostedZoneId: !Ref PRHostedZoneId

  Route53FailoverRecordSecondary: # Route 53 Failover DNS Record for backup api gateway
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Ref HostedZoneName
      Name: !Ref DRSUBDomainName
      Type: A
      SetIdentifier: Secondary
      Failover: SECONDARY
      AliasTarget:
        DNSName: !Ref DRAPIDomainName
        HostedZoneId: !Ref DRHostedZoneId

  PrimaryApiHealthAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: PrimaryAPI-Unhealthy
      MetricName: HealthCheckStatus
      Namespace: AWS/Route53
      Dimensions:
        - Name: HealthCheckId
          Value: !Ref Route53HealthCheck
      Statistic: Minimum
      ComparisonOperator: LessThanThreshold
      Threshold: 1  # Triggers when the health check fails
      Period: 30  # Evaluate every 30 seconds
      EvaluationPeriods: 2  # Trigger if unhealthy for 2 minutes
      AlarmActions:
        - !Ref SNSFailoverTopic  # Send sns notification

  SNSFailoverTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${AWS::StackName}-FailoverTopic
      DisplayName: Failover Alerts

  SNSEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      Endpoint: !Ref AdminEmail
      TopicArn: !Ref SNSFailoverTopic

  SNSLambdaSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: lambda
      Endpoint: !GetAtt FailoverLambda.Arn
      TopicArn: !Ref SNSFailoverTopic

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref FailoverLambda
      Principal: sns.amazonaws.com
      SourceArn: !Ref SNSFailoverTopic

  FailoverLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: FailoverToSecondary
      CodeUri: failover
      Handler: failoverLambdaHandler.lambda_handler
      Role: !GetAtt FailoverLambdaRole.Arn
      Environment:
        Variables:
          HOSTED_ZONE_ID: !Ref HostedZoneId
          HOSTED_ZONE_NAME: !Ref HostedZoneName
          DR_HOSTED_ZONE_ID: !Ref DRHostedZoneId
          DR_API_DOMAIN_NAME: !Ref DRAPIDomainName
          SecondaryUserPoolId: !Ref SecondaryUserPoolId
          DRRegion: !Ref DRRegion
          PrimaryRegion: !Ref PrimaryRegion
          SNSNotificationTopicSecondary: !Ref SNSNotificationTopicSecondary
          SNSNotificationTopicPrimary: !Ref SNSNotificationTopicPrimary
          DRCognitoAuthEndpoint: !Ref DRCognitoAuthEndpoint
          DRCallBackUrlEndpoint: !Ref DRCallBackUrlEndpoint
          DRClientId: !Ref DRClientId
          DRClientSecret: !Ref DRClientSecret
          DRWebsocketEndpoint: !Ref DRWebsocketEndpoint

  FailoverLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CloudWatchLogsPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*:*
        - PolicyName: CognitoPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - cognito-idp:ListUsers
                Resource: !Sub arn:aws:cognito-idp:${DRRegion}:${AWS::AccountId}:userpool/${SecondaryUserPoolId}
        - PolicyName: SNSPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sns:*
                Resource:
                  - !Ref SNSNotificationTopicSecondary
                  - !Ref SNSNotificationTopicPrimary
        - PolicyName: SSMPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ssm:PutParameter
                Resource:
                  - !Sub arn:aws:cognito-idp:${PrimaryRegion}:${AWS::AccountId}:parameter/photoblog/*